// Generated by CoffeeScript 1.6.3
(function() {
  describe("Query", function() {
    var a, b, c, d, e;
    a = b = c = d = e = null;
    beforeEach(function() {
      a = {
        'x': 'y',
        'foo': 9,
        'bar': "xxx",
        'ding': [2, 4, 8],
        'dong': -10,
        'bang': {
          'foo': 8
        }
      };
      b = {
        'x': 'y',
        'foo': 0,
        'bar': "yyy",
        'ding': [1, 3, 5, 7],
        'bang': {
          'foo': 0,
          'lst': [1, 2, 3]
        }
      };
      c = {
        'x': 'y',
        'foo': 1,
        'bar': "zzzz",
        'ding': [1, 3, 5, 7],
        'bang': {
          'foo': 8,
          'lst': [1, 2, 3]
        }
      };
      d = {
        'type': 'food',
        qty: 354,
        price: 5.95
      };
      return e = {
        'type': 'food',
        qty: 254,
        price: 10.32
      };
    });
    it("empty", function() {
      var m;
      m = Pongo.Query({});
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(true);
      expect(m(c)).toBe(true);
      m = Pongo.Query();
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(true);
      return expect(m(c)).toBe(true);
    });
    it("scalar equality", function() {
      var m;
      m = Pongo.Query({
        'foo': 9
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(false);
    });
    it("with regex", function() {
      var m;
      m = Pongo.Query({
        'bar': /^z+$/
      });
      expect(m(a)).toBe(false);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(true);
    });
    it("perform compound queries", function() {
      var m;
      m = Pongo.Query({
        'x': 'y',
        'foo': 0
      });
      expect(m(a)).toBe(false);
      expect(m(b)).toBe(true);
      return expect(m(c)).toBe(false);
    });
    it("in arrays", function() {
      var m;
      m = Pongo.Query({
        'ding': 4
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      expect(m(c)).toBe(false);
      m = Pongo.Query({
        'ding.1': 3
      });
      expect(m(a)).toBe(false);
      expect(m(b)).toBe(true);
      return expect(m(c)).toBe(true);
    });
    it("documents", function() {
      var m;
      m = Pongo.Query({
        'bang': {
          'foo': 8
        }
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(false);
    });
    it("in nested documents", function() {
      var m;
      m = Pongo.Query({
        'bang.foo': 8
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(true);
    });
    it("works with $in operator", function() {
      var m;
      m = Pongo.Query({
        'bar': {
          '$in': ['xxx', 'zzzz']
        }
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(true);
    });
    it("works with $or operator", function() {
      var m;
      m = Pongo.Query({
        '$or': [
          {
            'bar': 'xxx'
          }, {
            'bar': 'zzzz'
          }
        ]
      });
      expect(m(a)).toBe(true);
      expect(m(b)).toBe(false);
      return expect(m(c)).toBe(true);
    });
    return it("works with comlex queries", function() {
      var m;
      m = Pongo.Query({
        type: 'food',
        $or: [
          {
            qty: {
              $gt: 100
            }
          }, {
            price: {
              $lt: 9.95
            }
          }
        ]
      });
      expect(m(a)).toBe(false);
      expect(m(b)).toBe(false);
      expect(m(c)).toBe(false);
      expect(m(d)).toBe(true);
      expect(m(e)).toBe(true);
      m = Pongo.Query({
        type: 'food',
        $and: [
          {
            qty: {
              $gt: 100
            }
          }, {
            price: {
              $lt: 9.95
            }
          }
        ]
      });
      expect(m(a)).toBe(false);
      expect(m(b)).toBe(false);
      expect(m(c)).toBe(false);
      expect(m(d)).toBe(true);
      return expect(m(e)).toBe(false);
    });
  });

}).call(this);
